# Generated by Django 3.0.5 on 2020-05-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiRest', '0003_auto_20200502_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hamburguesa',
            name='ingrediente',
        ),
        migrations.AddField(
            model_name='hamburguesa',
            name='ingrediente',
            field=models.ManyToManyField(to='ApiRest.Ingrediente'),
        ),
    ]
