# Generated by Django 3.0.5 on 2020-05-03 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiRest', '0004_auto_20200502_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hamburguesa',
            old_name='ingrediente',
            new_name='ingredientes',
        ),
    ]
